application:
  info:
    app:
      name: '@project.artifactId@'
      version: '@project.version@'
      description: '@project.description@'
      copyright: '2023'
  configuration:
    analysis:
      # precision: 5
      trend-deep: 10
      trend-heat: 0.4
    # view:
    #   elements-by-page: 5
    security:
      enabled: ${rest.security.enabled}

logging:
  pattern:
    console: '%d %-5level %logger : %msg%n'
  level:
    com.shagui.analysis: DEBUG
    io.swagger.models.parameters.AbstractSerializableParameter: TRACE

spring:
  application:
    name: '@project.artifactId@'
  banner:
    location: classpath:/banner/spring-boot-banner.txt
  output:
    ansi:
      enabled: ALWAYS
  sql:
    init:
      mode: embedded
  jpa:
    open-in-view: true

springdoc:
  swagger-ui:
    enabled: true
    csrf:
      enabled: true
    operationsSorter: alpha
    tags-sorter: alpha
  packages-to-scan: com.shagui.sdc.controller
  paths-to-match: /api/**

rest:
  security:
    enabled: true
    issuerUri: http://localhost:9092/rws-security
    api-matcher:
      - api: /api/analysis/**
        roles:
          - ADMIN
          - ROLE_ADMIN
      - api: /api/**
      - api: /api/sse/**
        public: true
      - api: /api/public/**
        public: true
      - api: /v3/api-docs/**
      - api: /swagger.json
      - api: /swagger-ui.html
      - api: /swagger-ui/**
        public: true
      - api: /swagger-resources/**
        public: true
      - api: /webjars/**
      - api: /h2-console/**
      - api: /h2-ui/**
    cors:
      allowed-origins: '*'
      allowed-headers: '*'
      allowed-methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      max-age: 3600

management:
  endpoints:
    jmx:
      exposure:
        include: health,info,metrics,prometheus
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    shutdown:
      access: none

services:
  no-uri: http://no-uri

feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 10000
        loggerLevel: basic
