rest:
  security:
    enabled: false
    issuer-uri: http://localhost:9092/rws-security
    api-matcher:
      - api: /api/**
      - api: /api/public/**
        public: true
      - api: /v3/api-docs/**
      - api: /swagger.json
      - api: /swagger-ui.html
      - api: /swagger-ui/**
      - api: /swagger-resources/**
      - api: /webjars/**
