rest:
  security:
    issuerUri: http://localhost:9092/rws-security
    api-matcher:
      - /api/**
      - /v3/api-docs/**
      - /swagger.json
      - /swagger-ui.html
      - /swagger-ui/**
      - /swagger-resources/**
      - /webjars/**
      - /h2-console/**
      - /h2-ui/**
