export enum StateColors {
  CRITICAL = '#dc3149',
  RISK = '#efbe25',
  ACCEPTABLE = '#1e8927',
  PERFECT = '#006192'
}

export const BACKGROUND_CHART_COLOR = '#A9C9DA';
export const BACKGROUND_DEPARTMENT_COLOR = '#CEC3D9';
export const BACKGROUND_SQUAD_COLOR = BACKGROUND_CHART_COLOR;
