export enum ContextDataInfo {
  APPLICATIONS_DATA = 'APPLICATIONS_DATA',
  DEPARTMENTS_DATA = 'DEPARTMENTS_DATA',
  BREADCRUMBS_DATA = 'BREADCRUMBS_DATA',
  SQUADS_DATA = 'SQUADS_DATA',
  METRICS_DATA = 'METRICS_DATA'
}
