export const SCHEDULER_PERIOD = 1 * 60 * 1000; // Minutes

export enum ContextDataInfo {
  APP_CONFIG = 'APP_CONFIG',
  APPLICATIONS_DATA = 'APPLICATIONS_DATA',
  BREADCRUMBS_DATA = 'BREADCRUMBS_DATA',
  DEPARTMENTS_DATA = 'DEPARTMENTS_DATA',
  METRICS_DATA = 'METRICS_DATA',
  OVERLAY_DATA = 'OVERLAY_DATA',
  SQUADS_DATA = 'SQUADS_DATA'
}
